spring.application.name=raven
server.port=8080
spring.main.banner-mode=off

raven.config.path=config/raven.yaml
raven.neo4j.host=localhost
raven.neo4j.port=7687
raven.qdrant.host=localhost
raven.qdrant.http-port=6333
raven.qdrant.grpc-port=6334
raven.mongodb.host=localhost
raven.mongodb.port=27017

spring.data.mongodb.host=${raven.mongodb.host}
spring.data.mongodb.port=${raven.mongodb.port}
spring.data.mongodb.database=raven
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
